"""Add confirmation date to Call table

Revision ID: 39cab1b8f985
Revises: 5fcdb6caa496
Create Date: 2019-05-03 22:11:41.212076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cab1b8f985'
down_revision = '5fcdb6caa496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('confirmation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'confirmation_date')
    # ### end Alembic commands ###
