"""FAQ Table

Revision ID: 5fcdb6caa496
Revises: 3a6ddf40470d
Create Date: 2019-05-03 16:35:48.240989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcdb6caa496'
down_revision = '3a6ddf40470d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FAQ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_ru', sa.String(), nullable=True),
    sa.Column('text_uz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FAQ')
    # ### end Alembic commands ###
