"""ChannelPresentations table

Revision ID: 87bc0d7b9eb3
Revises: 4dccd2be77b5
Create Date: 2019-05-10 18:33:21.142893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bc0d7b9eb3'
down_revision = '4dccd2be77b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_presentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_presentations')
    # ### end Alembic commands ###
