"""Confirmed field and one-to-many relationship for user and calls

Revision ID: cc2b3932b460
Revises: 98f240538437
Create Date: 2019-05-02 15:38:59.102987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2b3932b460'
down_revision = '98f240538437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('calls', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calls', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_column('calls', 'user_id')
    op.drop_column('calls', 'confirmed')
    # ### end Alembic commands ###
